enabled:
  title: Processor Settings
  type: container
  tags: [ hide-title, non-essential ]
  children:
    gpu_freq:
      type: mode
      title: GPU Frequency
      hint: >-
        Pins the GPU to a certain frequency.
        Helps in certain games that are CPU or GPU heavy
        by shifting power to or from the GPU.
        Has a minor effect.
      default: auto
      modes:
        auto:
          type: container
          title: Auto
          hint: >-
            Lets the GPU manage its own frequency.
        upper:
          type: container
          title: Max Limit
          hint: >-
            Limits the maximum frequency of the GPU.
          children:
            frequency: &freq
              type: int
              unit: MHz
              min: 300
              max: 2000
              step: 100
              default: 1000
              title: Maximum Frequency
        range:
          type: container
          title: Range
          hint: >-
            Sets the GPU frequency to a range.
          children:
            min:
              <<: *freq
              title: Minimum Frequency
            max:
              <<: *freq
              title: Maximum Frequency
        manual:
          type: container
          title: Fixed
          hint: >-
            Pins the GPU to a certain frequency (not recommended).
          children:
            frequency:
              <<: *freq
              title: Frequency

core:
  type: container
  children:
    amd_energy_enable:
      title: Enable energy management
      type: bool
      default: False
      hint: >-
        Handheld daemon will manage the power preferences for the system,
        including Governor, Boost, GPU frequency, and EPP.
        In addition, Handheld daemon will launch a PPD service to replace
        PPD's role in the system. 

    amd_energy_ppd:
      title: Enable PPD Emulation (KDE/Gnome Power)
      type: bool
      default: False
      hint: >-
        Enable PPD service to manage the power preferences for the system.